"""empty message

Revision ID: 644b2741c65c
Revises: 9f6106fbf78d
Create Date: 2023-12-17 21:35:50.172343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '644b2741c65c'
down_revision = '9f6106fbf78d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('seniority',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('seniority',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
